### ISSUE TITLE
フロントプロジェクトの雛形

### ISSUE THREAD

**Issue by tetsuyanh** [foodbank-ymg/thanks-web-frontend#1]
Nextjsの最新13で。appDirectoryは`next export`がまだできないみたいなので使わない。
Typescriptも。トップページのデフォルトを消して簡素にh1タグぐらいにする。
CSSも適当に。
仮）`<h1 id="title">フードバンク山口ありがとうWeb</h1>`

**Comment by Nekodigi** [comment]
Tailwind CSSの導入まで行いました。
サイトの大まかな構造が分かった方が作りやすいと思うのですが、デザインの概要はいつ頃完成しますか？

**Comment by tetsuyanh** [comment]
@Nekodigi デザインは完全に茄子川さん待ちなので、バックエンドの方をタスク用意します。そちらを消化していきましょう。
