### ISSUE TITLE
トップページの「最近のおたより」をマークアップする

### ISSUE THREAD

**Issue by tetsuyanh** [foodbank-ymg/thanks-web-frontend#11]
カード形式と表現されるので、PostCardというコンポーネトを作って、それを並べるのがよいです。

PC
<img width="432" alt="スクリーンショット 2023-04-28 13 54 57" src="https://user-images.githubusercontent.com/1460298/235057914-b899b69b-ed5d-4c17-b632-1cb1ab5d9eb2.png">

スマホ
カルーセル機能は、ライブラリを使う予定。（後日提案します）
<img width="326" alt="スクリーンショット 2023-04-28 13 55 08" src="https://user-images.githubusercontent.com/1460298/235057936-b5354ea0-fc15-436a-8d1c-d04b782faee9.png">

**Comment by KAZU0302** [comment]
@tetsuyanh 
カルーセル機能のプログラムがどこにあるかわからないのですが、どこにありますか？
