### ISSUE TITLE
環境変数で投稿データのフェッチ先を切り替える

### ISSUE THREAD

**Issue by tetsuyanh** [foodbank-ymg/thanks-web-frontend#21]
参考となるリポジトリの閲覧を許可しました。
このような感じです。
https://github.com/thwoo-inc/hiraga-jun.site/blob/main/src/pages/news/index.tsx#L49
https://github.com/thwoo-inc/hiraga-jun.site/blob/main/.github/workflows/firebase-hosting-dispatch-develop.yml#L24

条件式は上と変えたいです。
`NEXT_PUBLIC_APP_ENV`＝`DEVELOPMENT`or`PRODUCTION`の場合、Firestoreからフェッチ。
それ以外は、現行の静的なダミーデータ。（ローカルはあまり環境変数の設定など意識/準備させない）

GitHubのActionsにFirestoreにアクセスできるように環境変数をセットしておきました。
GOOGLE_CREDENTIALS_DEV={secretなjson}

**Comment by Nekodigi** [comment]
Frontendから記事情報を取得する際は、BackendのAPIを使うのではなく、Firestoreから直接読み取るのですね。

**Comment by tetsuyanh** [comment]
@tetsuyanh はい。サーバー上で事前レンダリングするので、Adminで叩けるので。
