### ISSUE TITLE
このサイトについてページの「関わっている団体」部分の修正

### ISSUE THREAD

**Issue by tetsuyanh** [foodbank-ymg/thanks-web-frontend#51]
![Uploading スクリーンショット 2023-11-03 17.44.04.png…]()

**Comment by KAZU0302** [comment]
@tetsuyanh 
デザインや幅の値が書いてあるスクリーンショットをいただけると嬉しいです。よろしくお願いします。

**Comment by tetsuyanh** [comment]
@KAZU0302 
![スクリーンショット 2023-11-10 22 41 50](https://github.com/foodbank-ymg/thanks-web-frontend/assets/1460298/4673fdfa-9919-4645-839a-f8b55f7e3421)

![スクリーンショット 2023-11-10 22 41 56](https://github.com/foodbank-ymg/thanks-web-frontend/assets/1460298/90a855f6-0826-4aa4-af17-7ac02863adfd)

![スクリーンショット 2023-11-10 22 42 01](https://github.com/foodbank-ymg/thanks-web-frontend/assets/1460298/4b388957-dd57-459a-bc24-b1d72b4a5cc5)

**Comment by KAZU0302** [comment]
@tetsuyanh 
何度も申し訳ございません。スマホの時のスクリーンショットもいただきたいです。

**Comment by tetsuyanh** [comment]
@KAZU0302 
スマホの時はデザインないです。多分こうしたほうがいいはず、って感じで組んでもらって大丈夫です。

**Comment by tetsuyanh** [comment]
@KAZU0302 私の方で作業しました↑PCも不要そうな所を削ぎ落としますね。
